set -x

# If you are using vllm<=0.6.3, you might need to set the following environment variable to avoid bugs:
# export VLLM_ATTENTION_BACKEND=XFORMERS

python3 -m recipe.sgrpo.main_sgrpo \
    algorithm.adv_estimator=grpo \
    data.train_files=$HOME/data/dapo-math-17k-boxed.parquet \
    data.val_files=$HOME/data/test_60.parquet \
    data.train_batch_size=64 \
    data.max_prompt_length=10240 \
    data.max_response_length=10240 \
    data.filter_overlong_prompts=False \
    data.truncation='error' \
    actor_rollout_ref.model.path=$HOME/models/Qwen3-8B \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=4 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=2 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.rollout.order=5 \
    actor_rollout_ref.rollout.prune_tree=True \
    actor_rollout_ref.rollout.finder_style=redundant \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=32 \
    actor_rollout_ref.ref.log_prob_use_dynamic_bsz=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.use_kl_in_reward=False \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.entropy_driven_step_split=True \
    trainer.top_n_entropy_tokens=2 \
    trainer.output_sampling_tree=True \
    trainer.output_rollout_data=False \
    trainer.output_validation_data=True \
    trainer.val_before_train=True \
    trainer.project_name='sgrpo_qwen3_8b_math17k' \
    trainer.experiment_name='n5_d4_pruned_entropy_driven_non_thinking_8xh100' \
    trainer.resume_mode=disable \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=2 \
    trainer.save_freq=100 \
    trainer.test_freq=1 \
    trainer.total_epochs=10 $@
